---

- name: Install Amazon SSM Agent
  yum:
    name: https://s3.eu-central-1.amazonaws.com/amazon-ssm-eu-central-1/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present

- name: Enable Amazon SSM Agent
  systemd:
    name: amazon-ssm-agent
    enabled: yes
    masked: no

