---

- name: Set default value for PASS_MAX_DAYS
  replace:
    dest: /etc/login.defs
    regexp: "^PASS_MAX_DAYS.*$"
    replace: "PASS_MAX_DAYS   99999"

- name: Set default value for PASS_MIN_DAYS
  replace:
    dest: /etc/login.defs
    regexp: "^PASS_MIN_DAYS.*$"
    replace: "PASS_MIN_DAYS   0"

