---

- name: Check input variables
  hosts: localhost
  become: no
  tasks:
    - fail:
        msg: "You must specify app_environment variable when running ansible-playbook."
      when: app_environment is not defined or app_environment == ''

- name: Run common tasks to prepare RHEL for usage
  hosts: all
  become: yes
  roles:
    - common
  tags:
    - common

- name: Configure sshd
  hosts: all
  become: yes
  roles:
    - sshd
  tags:
    - sshd

- name: Configure amazon-ssm-agent
  hosts: all
  become: yes
  roles:
    - amazon-ssm-agent
  tags:
    - amazon-ssm-agent

