---

- name: Run common tasks to prepare RHEL for usage
  hosts: all
  become: yes
  roles:
    - common
  tags:
    - common

- name: Configure sshd
  hosts: all
  become: yes
  roles:
    - sshd
  tags:
    - sshd

- name: Configure amazon-ssm-agent
  hosts: all
  become: yes
  roles:
    - amazon-ssm-agent
  tags:
    - amazon-ssm-agent

